language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r dev_requirements.txt
script:
  - pytest tests.py
after_success: codecov
sudo: required
services:
  - docker
env:
  - TRAVIS=yes
before_install:
  - docker pull postgres:9.6
  - docker rm $(docker ps -a -q)
  - docker run -d -e POSTGRES_PASSWORD=pass -e POSTGRES_USER=user -e POSTGRES_DB=test_db --rm --name pq_test_db -p 127.0.0.1:5432:5432 postgres:9.6
  - docker ps -a
