language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r dev_requirements.txt
script:
  - pytest tests.py
after_success: codecov
sudo: required
services:
  - docker
before_install:
  - docker pull postgres:9.6
  - docker run -d postgres:9.6 --name pq_test_db -e POSTGRES_PASSWORD=pass -e POSTGRES_USER=user -e POSTGRES_DB=test_db
